# Generated by Django 4.0.4 on 2022-05-04 01:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegUser',
            fields=[
                ('firstname', models.CharField(max_length=255, verbose_name='First name')),
                ('lastname', models.CharField(max_length=255, verbose_name='Last name')),
                ('user_id', models.PositiveIntegerField(default=1, primary_key=True, serialize=False)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.MinLengthValidator(10)])),
                ('username', models.CharField(max_length=255, verbose_name='Username')),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
